### ISSUE TITLE
Difficult building on Windows

### ISSUE THREAD

**Issue by jamestunnell** [xthexder/go-jack#25]
When I first tried building one of the examples on Windows 10 (with mingw-w64), I go this compile error:
![image](https://user-images.githubusercontent.com/2146252/144107133-85675d9d-44be-4b04-aea0-e29c968420ca.png)

To get around this issue, I modified the jack.go that was installed from the Go module, adding flags with the path for JACK2 libraries and headers:
![image](https://user-images.githubusercontent.com/2146252/144107450-821a8389-fdc0-416b-a308-27ea438aa75e.png)

After that the example built fine. Maybe I was doing something wrong before? Or maybe jack.go can be [more platform-independent by using pkg-config](https://stackoverflow.com/questions/16931700/is-it-possible-to-use-environment-variables-in-a-cgo-cflags-comment)?

**Comment by xthexder** [comment]
I've added the additional flags, since they're the default install location on Win64. It seems to build and run with fairly minimal setup now.
