### ISSUE TITLE
Passthrough exemple not working depending on the input

### ISSUE THREAD

**Issue by B33low** [xthexder/go-jack#29]
Hello, I tried to use the pass-through example. If it is working when I am routing the sound from my yeti, but it is not working for any other sources (firefox, discord, scream, ...). Is it a known problem or do anyone have a clue where I should look for solving this ?

I am using pipewire on linux and haven't modified the example.

**Comment by B33low** [comment]
After some testing I got a bit more insight on what is going on:
If I connect my yeti at the input and ear myself and then (while the microphone output is still connected to the passthrough input) connect any other source to the passthrough input, it works. Like if the SetProcessCallback function is not called when the microphone output is not connected tot the input.

**Comment by xthexder** [comment]
Firefox, Discord, etc... are likely using another audio driver such as Pulseaudio or Alsa. You can check your connections using another Jack  client (I've used the  `patchage` client in the past). You'll probably need to install and connect the pulseaudio jack bridge to forward audio.

I'd expect Jack will stop calling the process callback if no clients are connected and there is no audio signal.
