### ISSUE TITLE
MIDI examples?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [xthexder/go-jack#31]
Hi! Could you provide an example of how to make a Go program that reads MIDI from one jack port, and sends MIDI to another?

The README mentions `jack_midi_event_get()`, but I don't see it mentioned on https://jackaudio.org/api/jack_8h.html; and I'd like to know how to properly setup an event-based solution with low-latency so that MIDI events get processed in realtime.

For example, a transposing program that reads MIDI notes from one port, and sends them out on another port, transposed N half-steps higher/lower.

Or if a full example of code is not easy, just a few sentences describing how to do it would be cool!

**Comment by xthexder** [comment]
The jack midi functions are in a separate header. You can find the docs here: https://jackaudio.org/api/midiport_8h.html

There is already a midi passthrough example here: https://github.com/xthexder/go-jack/blob/master/example/midipassthrough.go
You should be able to modify the midi events however you like using that as a base.

You should know, jack processes midi events in batches or "frames", so your code will have to handle potentially multiple midi events per invocation, which is a little different from a typical event-based system.

**Comment by GeoffreyPlitt** [comment]
Massively helpful, thank you!
